#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

#meshing
runApplication blockMesh

#run
cp -r 0.orig/ 0
runApplication setFields
runApplication decomposePar
printf "Running kistlerInterFlow\n"
mpirun -np 2 kistlerInterFlow -parallel > log.kistlerInterFlow
runApplication reconstructPar
#------------------------------------------------------------------------------
